<?php
$pdf = new FPDF();
$pdf->AddPage();

// Set precise margins
$pdf->SetMargins(10, 10, 10);
$pdf->SetAutoPageBreak(true, 10);

$pdf->SetFont('Arial','B',16);
$pdf->SetXY(0, 10);
$pdf->Cell(0,10,'LAB AUTOMATION TEST REPORT',0,1,'C');
$pdf->Ln(8);

// Test Information Table - Perfectly aligned columns
$pdf->SetFont('Arial','B',12);
$pdf->SetFillColor(240, 240, 240);
$pdf->Cell(0,8,'TEST INFORMATION',1,1,'C',true);

// First row - perfectly aligned
$pdf->SetFont('Arial','B',10);
$pdf->Cell(45,7,'Test ID:', 'L',0,'L');
$pdf->SetFont('Arial','',10);
$pdf->Cell(45,7,$test_id,0,0,'L');
$pdf->SetFont('Arial','B',10);
$pdf->Cell(45,7,'Tester ID:',0,0,'L');
$pdf->SetFont('Arial','',10);
$pdf->Cell(55,7,$tester_id, 'R',1,'L');

// Second row
$pdf->SetFont('Arial','B',10);
$pdf->Cell(45,7,'Product ID:', 'L',0,'L');
$pdf->SetFont('Arial','',10);
$pdf->Cell(45,7,$product_id,0,0,'L');
$pdf->SetFont('Arial','B',10);
$pdf->Cell(45,7,'Date:',0,0,'L');
$pdf->SetFont('Arial','',10);
$pdf->Cell(55,7,date('Y-m-d H:i:s'), 'R',1,'L');

// Third row
$pdf->SetFont('Arial','B',10);
$pdf->Cell(45,7,'Product Name:', 'L',0,'L');
$pdf->SetFont('Arial','',10);
$pdf->Cell(145,7,$product_name, 'R',1,'L');

$pdf->Ln(8);

// Criteria Evaluation Table - Perfect column alignment
$pdf->SetFont('Arial','B',12);
$pdf->SetFillColor(240, 240, 240);
$pdf->Cell(0,8,'CRITERIA EVALUATION',1,1,'C',true);

// Table Headers - Exactly aligned columns
$pdf->SetFont('Arial','B',10);
$pdf->Cell(70,7,'CRITERIA', 'L',0,'C');
$pdf->Cell(30,7,'MAX MARKS',0,0,'C');
$pdf->Cell(40,7,'MARKS OBTAINED',0,0,'C');
$pdf->Cell(50,7,'SCORE %', 'R',1,'C');

$criteriaLabels = array('Accuracy', 'Durability', 'Usability', 'Safety', 'Efficiency');

for($i=0; $i<5; $i++) {
    $pdf->SetFont('Arial','',10);
    $pdf->Cell(70,7,$criteriaLabels[$i], 'L',0,'L');
    
    // Max Marks (always 5) - Centered
    $pdf->SetFont('Arial','',10);
    $pdf->Cell(30,7,'5',0,0,'C');
    
    // Marks Obtained - Centered
    $pdf->SetFont('Arial','B',10);
    $pdf->Cell(40,7,$criteria[$i],0,0,'C');
    
    // Score Percentage - Centered
    $percentage = ($criteria[$i] / 5) * 100;
    $pdf->SetFont('Arial','',10);
    $pdf->Cell(50,7,$percentage . '%', 'R',1,'C');
}

$pdf->Ln(8);

// Test Results Summary - Perfect alignment
$pdf->SetFont('Arial','B',12);
$pdf->SetFillColor(240, 240, 240);
$pdf->Cell(0,8,'TEST RESULTS SUMMARY',1,1,'C',true);

// Calculate percentage
$percentageScore = ($totalScore / 25) * 100;

// Total Score row
$pdf->SetFont('Arial','B',11);
$pdf->Cell(50,10,'Total Score:', 'L',0,'L');
$pdf->SetFont('Arial','B',12);
$pdf->Cell(140,10,"$totalScore / 25 ($percentageScore%)", 'R',1,'C');

// Final Result row
$pdf->SetFont('Arial','B',11);
$pdf->Cell(50,10,'Final Result:', 'L',0,'L');

// Color code the result
if(strtoupper($results) == 'PASSED') {
    $pdf->SetTextColor(40, 167, 69);
} else {
    $pdf->SetTextColor(220, 53, 69);
}

$pdf->SetFont('Arial','B',12);
$pdf->Cell(140,10,strtoupper($results), 'R',1,'C',true);

// Reset colors
$pdf->SetFillColor(255, 255, 255);
$pdf->SetTextColor(0, 0, 0);

$pdf->Ln(8);

// Remarks Section
$pdf->SetFont('Arial','B',12);
$pdf->SetFillColor(240, 240, 240);
$pdf->Cell(0,8,'REMARKS & OBSERVATIONS',1,1,'C',true);
$pdf->SetFont('Arial','',10);

// Get current Y position to calculate available space
$startY = $pdf->GetY();
$maxY = 100; // Leave space for footer

// Calculate height for remarks to fit perfectly
$availableHeight = $maxY - $startY - 10;

// Create a bordered cell for remarks
$pdf->MultiCell(0,6, $remarks, 1, 'L');

// Footer - positioned perfectly at bottom
$pdf->SetY(-25);
$pdf->SetFont('Arial','I',8);
$pdf->Cell(0,5,'Generated by Lab Automation System | ' . date('Y-m-d H:i:s'),0,1,'C');
$pdf->Cell(0,5,'Confidential Test Document - Page 1 of 1',0,1,'C');
?>