<?php
$pdf = new FPDF();
$pdf->AddPage();

// Set precise margins
$pdf->SetMargins(10, 10, 10);
$pdf->SetAutoPageBreak(true, 10);

$pdf->SetFont('Arial','B',16);
$pdf->SetXY(0, 10);
$pdf->Cell(0,10,'LAB AUTOMATION TEST REPORT',0,1,'C');
$pdf->Ln(8);

// Test Information Table
$pdf->SetFont('Arial','B',12);
$pdf->SetFillColor(240, 240, 240);
$pdf->Cell(0,8,'TEST INFORMATION',1,1,'C',true);

// First row
$pdf->SetFont('Arial','B',10);
$pdf->Cell(45,7,'Test ID:', 'L',0,'L');
$pdf->SetFont('Arial','',10);
$pdf->Cell(45,7,$test_id,0,0,'L');
$pdf->SetFont('Arial','B',10);
$pdf->Cell(45,7,'Tester ID:',0,0,'L');
$pdf->SetFont('Arial','',10);
$pdf->Cell(55,7,$tester_id, 'R',1,'L');

// Second row
$pdf->SetFont('Arial','B',10);
$pdf->Cell(45,7,'Product ID:', 'L',0,'L');
$pdf->SetFont('Arial','',10);
$pdf->Cell(45,7,$product_id,0,0,'L');
$pdf->SetFont('Arial','B',10);
$pdf->Cell(45,7,'Date:',0,0,'L');
$pdf->SetFont('Arial','',10);
$pdf->Cell(55,7,date('Y-m-d H:i:s'), 'R',1,'L');

// Third row
$pdf->SetFont('Arial','B',10);
$pdf->Cell(45,7,'Product Name:', 'L',0,'L');
$pdf->SetFont('Arial','',10);
$pdf->Cell(145,7,$product_name, 'R',1,'L');

$pdf->Ln(8);

// Criteria Evaluation Table
$pdf->SetFont('Arial','B',12);
$pdf->SetFillColor(240, 240, 240);
$pdf->Cell(0,8,'CRITERIA EVALUATION',1,1,'C',true);

// Table Headers
$pdf->SetFont('Arial','B',10);
$pdf->Cell(70,7,'CRITERIA', 'L',0,'C');
$pdf->Cell(30,7,'MAX MARKS',0,0,'C');
$pdf->Cell(40,7,'MARKS OBTAINED',0,0,'C');
$pdf->Cell(50,7,'SCORE %', 'R',1,'C');

$criteriaLabels = ['Accuracy', 'Durability', 'Usability', 'Safety', 'Efficiency'];
$criteriaKeys   = ['accuracy','durability','usability','safety','efficiency'];

for($i=0; $i<5; $i++) {

    // FIX: Correct mapping from associative array
    $value = $criteria[$criteriaKeys[$i]];

    $pdf->SetFont('Arial','',10);
    $pdf->Cell(70,7,$criteriaLabels[$i], 'L',0,'L');
    
    // Max marks
    $pdf->SetFont('Arial','',10);
    $pdf->Cell(30,7,'5',0,0,'C');
    
    // Marks obtained
    $pdf->SetFont('Arial','B',10);
    $pdf->Cell(40,7,$value,0,0,'C');
    
    // Score percentage
    $percentage = ($value / 5) * 100;
    $pdf->SetFont('Arial','',10);
    $pdf->Cell(50,7,$percentage . '%', 'R',1,'C');
}

$pdf->Ln(8);

// Summary Section
$pdf->SetFont('Arial','B',12);
$pdf->SetFillColor(240, 240, 240);
$pdf->Cell(0,8,'TEST RESULTS SUMMARY',1,1,'C',true);

// Total score row
$percentageScore = ($totalScore / 25) * 100;

$pdf->SetFont('Arial','B',11);
$pdf->Cell(50,10,'Total Score:', 'L',0,'L');
$pdf->SetFont('Arial','B',12);
$pdf->Cell(140,10,"$totalScore / 25 ($percentageScore%)", 'R',1,'C');

// Final result row
$pdf->SetFont('Arial','B',11);
$pdf->Cell(50,10,'Final Result:', 'L',0,'L');

// Color
if(strtoupper($results) == 'PASS') {
    $pdf->SetTextColor(40, 167, 69);
} else {
    $pdf->SetTextColor(220, 53, 69);
}

$pdf->SetFont('Arial','B',12);
$pdf->Cell(140,10,strtoupper($results), 'R',1,'C',true);

// Reset color
$pdf->SetTextColor(0, 0, 0);
$pdf->SetFillColor(255, 255, 255);

$pdf->Ln(8);

// Remarks Section
$pdf->SetFont('Arial','B',12);
$pdf->SetFillColor(240, 240, 240);
$pdf->Cell(0,8,'REMARKS & OBSERVATIONS',1,1,'C',true);

$pdf->SetFont('Arial','',10);
$pdf->MultiCell(0,6, $remarks, 1, 'L');

// Footer
$pdf->SetY(-25);
$pdf->SetFont('Arial','I',8);
$pdf->Cell(0,5,'Generated by Lab Automation System | ' . date('Y-m-d H:i:s'),0,1,'C');
$pdf->Cell(0,5,'Confidential Test Document - Page 1 of 1',0,1,'C');
?>
